<a href="https://colab.research.google.com/github/ENRICOROBLESDELRIO/data_boot_camp_final_project/blob/enrico_branch/Machine_Learning_Model_1_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install --upgrade -q pygsheets

     |████████████████████████████████| 147 kB 5.5 MB/s 


# **Import data**

In [2]:
# Authenticator code

import google.auth
from google.colab import auth

auth.authenticate_user()
import pygsheets
credentials, _ = google.auth.default()
gc = pygsheets.client.Client(credentials)

In [3]:
# Libraries and dependencies

import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns
import math
from sklearn.metrics import accuracy_score
from google.colab import files

In [6]:
# Google Sheet with the data base of companies

sheet = gc.open_by_key('1wMcaDShdLmXnhfo6Co-rozlvo_hSw83A1BcO3nYcy8g')
worksheet = sheet.worksheet_by_title('Companies')

# get_all_values into a data frame
db_companies = worksheet.get_as_df()
db_companies.head() 

id_company  category  ...  increase_employees  increase_capital
0          A         1  ...                   5          12390000
1          B         2  ...                   0                 0
2          C         1  ...                 587         234950000
3          D         1  ...                  29          10250000
4          E         1  ...                   8           1600000

[5 rows x 30 columns]

In [7]:
# data types
db_companies.dtypes

id_company                    object
category                       int64
founding_year                  int64
seed_year                      int64
seed_amount                    int64
last_funding_year              int64
months_since_last_funding    float64
amount_last_funding            int64
support_company                int64
manufacture_equipment          int64
develop_new_tech               int64
grow_company                   int64
add_new_services               int64
develop_business               int64
financial_banking              int64
develop_products_services      int64
marketing_strategies           int64
expand_internationality        int64
consolidate_company            int64
increase_team                  int64
number_employees               int64
number_investors               int64
foreing_vc                     int64
local_vc                       int64
current_status                 int64
soonicorn                      int64
more100_employees              int64
r

In [8]:
# Google Sheet with the data base of founders

sheet_2 = gc.open_by_key('1wMcaDShdLmXnhfo6Co-rozlvo_hSw83A1BcO3nYcy8g')
worksheet = sheet_2.worksheet_by_title('Founders')

# get_all_values into a data frame
db_founders = worksheet.get_as_df()
db_founders.head() 

id_founder  id_company  ... foreing_work_experience foreing_founder
0           1           7  ...                                        
1           2          23  ...                                        
2           3         141  ...                                        
3           4         152  ...                                        
4           5         155  ...                                        

[5 rows x 38 columns]

In [9]:
# data types
db_founders.dtypes

id_founder                              int64
id_company                              int64
general_location                       object
manager_exp                            object
clevel_exp                             object
engineering_exp                        object
sales_exp                              object
finance_exp                            object
human_capital_exp                      object
marketing_exp                          object
consulting_exp                         object
founder_exp                            object
abroad_experience                      object
worked_on_plus100_company              object
software_exp                           object
insurance_exp                          object
agriculture_related_deg                object
business_deg                           object
entreprenueurship_deg                  object
financial_deg                          object
marketing_deg                          object
maths_engineering_deg             

In [10]:
# Google Sheet with the data base of VC Rounds 

sheet_2 = gc.open_by_key('1wMcaDShdLmXnhfo6Co-rozlvo_hSw83A1BcO3nYcy8g')
worksheet = sheet_2.worksheet_by_title('Rounds')

# get_all_values into a data frame
db_rounds = worksheet.get_as_df()
db_rounds.head()

id_company  round_year  ... consolidate_company  increase_team
0          A        2020  ...                   0              0
1          A        2021  ...                   0              0
2          B        2016  ...                   0              0
3          C        2014  ...                   0              0
4          C        2016  ...                   0              0

[5 rows x 15 columns]

In [11]:
# data types
db_rounds.dtypes

id_company                   object
round_year                    int64
round_amount                 object
support_company               int64
manufacture_equipment         int64
develop_new_tech              int64
grow_company                  int64
add_new_services              int64
develop_business              int64
financial_banking             int64
develop_products_services     int64
marketing_strategies          int64
expand_internationality       int64
consolidate_company           int64
increase_team                 int64
dtype: object

## **Random Forest**

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [13]:
# 1. Define features set
X = db_companies.copy()
X = X.drop(["more100_employees","id_company"], axis=1)
X.head()

category  founding_year  ...  increase_employees  increase_capital
0         1           2017  ...                   5          12390000
1         2           2013  ...                   0                 0
2         1           2014  ...                 587         234950000
3         1           2019  ...                  29          10250000
4         1           2014  ...                   8           1600000

[5 rows x 28 columns]

In [14]:
# 2. Define the target set. 
# Here, we're using the ravel() method, which performs the same procedure on our target set data as the values attribute.
y = db_companies["more100_employees"].ravel()
y[:5]

array([0, 0, 1, 0, 0])

When the train_test_split() function is executed, our data is split into a specific proportion of the original data sets. By default, our training and testing data sets are 75% and 25%, respectively, of the original data. Using the following code, we can see the data's 75-25 split.

In [15]:
# 3. Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [16]:
#Printings arrays

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8, 28)
(3, 28)
(8,)
(3,)


In [17]:
X_train.dtypes

category                       int64
founding_year                  int64
seed_year                      int64
seed_amount                    int64
last_funding_year              int64
months_since_last_funding    float64
amount_last_funding            int64
support_company                int64
manufacture_equipment          int64
develop_new_tech               int64
grow_company                   int64
add_new_services               int64
develop_business               int64
financial_banking              int64
develop_products_services      int64
marketing_strategies           int64
expand_internationality        int64
consolidate_company            int64
increase_team                  int64
number_employees               int64
number_investors               int64
foreing_vc                     int64
local_vc                       int64
current_status                 int64
soonicorn                      int64
rounds_funding_factor        float64
increase_employees             int64
i

In [18]:
X_train['increase_capital'] = pd.to_numeric(X_train.increase_capital, errors='coerce')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [19]:
X_train.dtypes

category                       int64
founding_year                  int64
seed_year                      int64
seed_amount                    int64
last_funding_year              int64
months_since_last_funding    float64
amount_last_funding            int64
support_company                int64
manufacture_equipment          int64
develop_new_tech               int64
grow_company                   int64
add_new_services               int64
develop_business               int64
financial_banking              int64
develop_products_services      int64
marketing_strategies           int64
expand_internationality        int64
consolidate_company            int64
increase_team                  int64
number_employees               int64
number_investors               int64
foreing_vc                     int64
local_vc                       int64
current_status                 int64
soonicorn                      int64
rounds_funding_factor        float64
increase_employees             int64
i

In [20]:
X_test.dtypes

category                       int64
founding_year                  int64
seed_year                      int64
seed_amount                    int64
last_funding_year              int64
months_since_last_funding    float64
amount_last_funding            int64
support_company                int64
manufacture_equipment          int64
develop_new_tech               int64
grow_company                   int64
add_new_services               int64
develop_business               int64
financial_banking              int64
develop_products_services      int64
marketing_strategies           int64
expand_internationality        int64
consolidate_company            int64
increase_team                  int64
number_employees               int64
number_investors               int64
foreing_vc                     int64
local_vc                       int64
current_status                 int64
soonicorn                      int64
rounds_funding_factor        float64
increase_employees             int64
i

In [21]:
X_test['increase_capital'] = pd.to_numeric(X_test.increase_capital, errors='coerce')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [22]:
# Creating StandardScaler instance
# Now that we have split our data into training and testing sets, we can scale the data using Scikit-learn's StandardScaler.

# Creating a StandardScaler instance.
scaler = StandardScaler()

# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [23]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=500, random_state=78)

In [24]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

**Making Predictions**

In [26]:
# Making predictions using the testing data
predictions = rf_model.predict(X_test_scaled)

In [27]:
predictions 

array([0, 0, 0])

**Model Evaluation**

In [28]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

cm_df

Predicted 0  Predicted 1
Actual 0            2            0
Actual 1            1            0

In [29]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.6666666666666666

In [30]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0            2            0
Actual 1            1            0

Accuracy Score : 0.6666666666666666
Classification Report
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       0.00      0.00      0.00         1

    accuracy                           0.67         3
   macro avg       0.33      0.50      0.40         3
weighted avg       0.44      0.67      0.53         3



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
